integrand <- function(x) {abs(sin(x))/x}
integrate(integrand, lower = 0, upper = 10)
plot(integrand, 0, 10)
library(rgl)
#spheres3d(x=1,y=2,z=1,radius=2)
#detach("package:rgl", unload = TRUE)
userinput <- readline(prompt = "Enter a function of x, y to graph: ")

x <- y <- seq(-2, 2, length= 20)
z <- eval(parse(text = paste("outer(x,y,function(x,y) {", userinput, "})")))
#colorlut <- terrain.colors(20, rev = TRUE)
#col <- colorlut[z]
surface3d(x,y,z, color="#BADA55")
eval(parse(text = paste("integrate(Vectorize(function(x) { integrate((function(y) {", userinput, "}), -2, 2)$value }), -2,2)")))

#integrate(Vectorize(function(x) { 
#integrate((function(y) { eval(parse(text = userinput)) }), 1, 2)$value }), 1,2)
#persp(x, y, z)
print("TRIPLE INTEGRAL: dzdydx")
cat("Enter (separated by commas) a function of x,y,z\n(inner function), lower then upper x bounds, lower then\nupper y bounds, and lower then upper z bounds: ")
wholeData <- readline()
splitData <- strsplit(wholeData, split = ",", fixed = TRUE)
eval(parse(text = paste("integrate(Vectorize(function(x) { integrate(Vectorize(function(y) { integrate(function(z) { ",splitData[[1]][1]," }, ",splitData[[1]][6],", ",splitData[[1]][7],")$value }), ",splitData[[1]][4],",",splitData[[1]][5],")$value }), ",splitData[[1]][2],",",splitData[[1]][3],")")))
print("FLUX COMPUTATION: ")
cat("Enter, separated by commas, g1, g2, g3 (where g(x,y) is the surface parametrization), x lower bound, x upper, y lower, y upper, f1, f2, f3 (where f(x,y,z) is the vector field): ")
wholeFluxData <- readline()
sfd <- strsplit(wholeFluxData, split = ",", fixed = TRUE)
#test flux computation
g <- list(sfd[[1]][1], sfd[[1]][2], sfd[[1]][3])
f <- list(sfd[[1]][8], sfd[[1]][9], sfd[[1]][10])
#g <- list("cos(x)*sin(y)", "sin(x)*sin(y)", "cos(y)")
#f <- list("x", "y", "z")
#print( eval(parse(text = paste("D(expression(", g[[1]], "), 'x')"))) )
tx <- list(eval(parse(text = paste("D(expression(", g[[1]], "), 'x')"))), eval(parse(text = paste("D(expression(", g[[2]], "), 'x')"))), eval(parse(text = paste("D(expression(", g[[3]], "), 'x')"))))
ty <- list(eval(parse(text = paste("D(expression(", g[[1]], "), 'y')"))), eval(parse(text = paste("D(expression(", g[[2]], "), 'y')"))), eval(parse(text = paste("D(expression(", g[[3]], "), 'y')"))))
txs <- lapply(tx, FUN = deparse)
tys <- lapply(ty, FUN = deparse)
stry1 <- gsub("x", "ax", f[[1]])
stry1 <- gsub("y", "by", stry1)
stry1 <- gsub("ax", paste("(", g[[1]], ")"), stry1)
stry1 <- gsub("by", paste("(", g[[2]], ")"), stry1)
stry1 <- gsub("z", paste("(", g[[3]], ")"), stry1)
stry2 <- gsub("x", "ax", f[[2]])
stry2 <- gsub("y", "by", stry2)
stry2 <- gsub("ax", paste("(", g[[1]], ")"), stry2)
stry2 <- gsub("by", paste("(", g[[2]], ")"), stry2)
stry2 <- gsub("z", paste("(", g[[3]], ")"), stry2)
stry3 <- gsub("x", "ax", f[[3]])
stry3 <- gsub("y", "by", stry3)
stry3 <- gsub("ax", paste("(", g[[1]], ")"), stry3)
stry3 <- gsub("by", paste("(", g[[2]], ")"), stry3)
stry3 <- gsub("z", paste("(", g[[3]], ")"), stry3)
FG <- list(stry1, stry2, stry3)
N <- list(eval(expression(parse(text = paste("(", txs[[2]], ")*(", tys[[3]], ")-(", txs[[3]], ")*(", tys[[2]], ")" )))), eval(expression(parse(text = paste("(", txs[[3]], ")*(", tys[[1]], ")-(", txs[[1]], ")*(", tys[[3]], ")" )))), eval(expression(parse(text = paste("(", txs[[1]], ")*(", tys[[2]], ")-(", txs[[2]], ")*(", tys[[1]], ")" )))))
Ns <- lapply(N, FUN = toString)
eval(parse(text = paste("integrate(Vectorize(function(x) { integrate(function(y) { (",Ns[[1]], ")*(", FG[[1]], ")+(", Ns[[2]], ")*(", FG[[2]], ")+(", Ns[[3]], ")*(", FG[[3]]  , ") }, ", sfd[[1]][6] ,",", sfd[[1]][7] ,")$value }), ", sfd[[1]][4] ,",", sfd[[1]][5] ,")")))
print("Surface area:")
eval(parse(text = paste("integrate(Vectorize(function(x) { integrate(function(y) { sqrt((", Ns[[1]], ")^2+(", Ns[[2]], ")^2+(", Ns[[3]] , ")^2) }, ", sfd[[1]][6] ,",", sfd[[1]][7] ,")$value }), ", sfd[[1]][4] ,",", sfd[[1]][5] ,")")))
integrate(Vectorize(function(x) { 
  integrate(function(y) { x*y }, 0,2*pi)$value }), 0,pi)
par(mfrow = c(3,1))
par(mfrow = c(1,1))
arrow3d(p0 = c(1,1,1), p1 = c(0,0,0))
#TODO: use this to graph vector field
xyz <- matrix(rnorm(300, sd=0.5),ncol=3)
plot3d(xyz)
arrow3d(xyz[1,],xyz[2,], col="red", s=1)
arrow3d(xyz[3,],xyz[4,], col="blue")
print("LINE INTEGRALS: ")
cat("Enter, separated by commas, r1, r2, r3 (where r(t) is a parametrization of a\nline), t lower bound, t upper bound, and f1, f2, f3 (where f(x,y,z) is a\nvector field)")
lineinput <- readline()
splitLineInput <- strsplit(lineinput, split = ",", fixed = TRUE)
rprime <- list(D(parse(text = splitLineInput[[1]][1]), "t"), D(parse(text = splitLineInput[[1]][2]), "t"), D(parse(text = splitLineInput[[1]][3]), "t"))
rprime <- lapply(rprime, deparse)
str1 <- gsub("x", paste("(", splitLineInput[[1]][1], ")"), splitLineInput[[1]][6])
str1 <- gsub("y", paste("(", splitLineInput[[1]][2], ")"), str1)
str1 <- gsub("z", paste("(", splitLineInput[[1]][3], ")"), str1)
str2 <- gsub("x", paste("(", splitLineInput[[1]][1], ")"), splitLineInput[[1]][7])
str2 <- gsub("y", paste("(", splitLineInput[[1]][2], ")"), str2)
str2 <- gsub("z", paste("(", splitLineInput[[1]][3], ")"), str2)
str3 <- gsub("x", paste("(", splitLineInput[[1]][1], ")"), splitLineInput[[1]][8])
str3 <- gsub("y", paste("(", splitLineInput[[1]][2], ")"), str3)
str3 <- gsub("z", paste("(", splitLineInput[[1]][3], ")"), str3)
FR <- list(str1,str2,str3)
eval(parse(text = paste("integrate(function(t){", FR[1], "*(", rprime[1], ")+", FR[2], "*(", rprime[2], ")+", FR[3], "*(", rprime[3] ,")}, ", splitLineInput[[1]][4], ",", splitLineInput[[1]][5] ,")")))
integrate(function(t){sin(t)}, 0, pi)
